export declare const listJobs: import("convex/server").RegisteredQuery<"public", {
    enabledOnly?: boolean | undefined;
    ownerUserId: string;
}, Promise<{
    _id: import("convex/values").GenericId<"cronJobs">;
    _creationTime: number;
    agentId?: string | undefined;
    description?: string | undefined;
    sessionKey?: string | undefined;
    wakeMode?: string | undefined;
    delivery?: ArrayBuffer | undefined;
    failureAlert?: any;
    deleteAfterRun?: boolean | undefined;
    createdByChannelId?: string | undefined;
    createdByConversationId?: string | undefined;
    createdByAccountId?: string | undefined;
    scheduleExpr?: string | undefined;
    scheduleTz?: string | undefined;
    scheduleStaggerMs?: number | undefined;
    scheduleEveryMs?: number | undefined;
    scheduleAnchorMs?: number | undefined;
    scheduleAt?: number | undefined;
    stateNextRunAtMs?: number | undefined;
    stateLastRunAtMs?: number | undefined;
    stateRunningAtMs?: number | undefined;
    stateLastStatus?: string | undefined;
    stateLastError?: string | undefined;
    stateScheduleErrorCount?: number | undefined;
    stateConsecutiveErrorCount?: number | undefined;
    stateLastFailureAlertAtMs?: number | undefined;
    stateLastDelivered?: boolean | undefined;
    stateLastDeliveryStatus?: string | undefined;
    stateLastDeliveryError?: string | undefined;
    name: string;
    enabled: boolean;
    sessionTarget: string;
    payload: ArrayBuffer;
    jobId: string;
    updatedAtMs: number;
    createdByKind: "owner" | "channel" | "legacy";
    ownerUserId: string;
    scheduleKind: "at" | "every" | "cron";
    createdAtMs: number;
}[]>>;
export declare const getJob: import("convex/server").RegisteredQuery<"public", {
    jobId: string;
    ownerUserId: string;
}, Promise<{
    _id: import("convex/values").GenericId<"cronJobs">;
    _creationTime: number;
    agentId?: string | undefined;
    description?: string | undefined;
    sessionKey?: string | undefined;
    wakeMode?: string | undefined;
    delivery?: ArrayBuffer | undefined;
    failureAlert?: any;
    deleteAfterRun?: boolean | undefined;
    createdByChannelId?: string | undefined;
    createdByConversationId?: string | undefined;
    createdByAccountId?: string | undefined;
    scheduleExpr?: string | undefined;
    scheduleTz?: string | undefined;
    scheduleStaggerMs?: number | undefined;
    scheduleEveryMs?: number | undefined;
    scheduleAnchorMs?: number | undefined;
    scheduleAt?: number | undefined;
    stateNextRunAtMs?: number | undefined;
    stateLastRunAtMs?: number | undefined;
    stateRunningAtMs?: number | undefined;
    stateLastStatus?: string | undefined;
    stateLastError?: string | undefined;
    stateScheduleErrorCount?: number | undefined;
    stateConsecutiveErrorCount?: number | undefined;
    stateLastFailureAlertAtMs?: number | undefined;
    stateLastDelivered?: boolean | undefined;
    stateLastDeliveryStatus?: string | undefined;
    stateLastDeliveryError?: string | undefined;
    name: string;
    enabled: boolean;
    sessionTarget: string;
    payload: ArrayBuffer;
    jobId: string;
    updatedAtMs: number;
    createdByKind: "owner" | "channel" | "legacy";
    ownerUserId: string;
    scheduleKind: "at" | "every" | "cron";
    createdAtMs: number;
} | null>>;
export declare const insertJob: import("convex/server").RegisteredMutation<"public", {
    agentId?: string | undefined;
    description?: string | undefined;
    sessionKey?: string | undefined;
    wakeMode?: string | undefined;
    delivery?: ArrayBuffer | undefined;
    failureAlert?: any;
    deleteAfterRun?: boolean | undefined;
    updatedAtMs?: number | undefined;
    createdByChannelId?: string | undefined;
    createdByConversationId?: string | undefined;
    createdByAccountId?: string | undefined;
    scheduleExpr?: string | undefined;
    scheduleTz?: string | undefined;
    scheduleStaggerMs?: number | undefined;
    scheduleEveryMs?: number | undefined;
    scheduleAnchorMs?: number | undefined;
    scheduleAt?: number | undefined;
    createdAtMs?: number | undefined;
    stateNextRunAtMs?: number | undefined;
    stateLastRunAtMs?: number | undefined;
    stateRunningAtMs?: number | undefined;
    stateLastStatus?: string | undefined;
    stateLastError?: string | undefined;
    stateScheduleErrorCount?: number | undefined;
    stateConsecutiveErrorCount?: number | undefined;
    stateLastFailureAlertAtMs?: number | undefined;
    stateLastDelivered?: boolean | undefined;
    stateLastDeliveryStatus?: string | undefined;
    stateLastDeliveryError?: string | undefined;
    name: string;
    enabled: boolean;
    sessionTarget: string;
    payload: ArrayBuffer;
    jobId: string;
    createdByKind: "owner" | "channel" | "legacy";
    ownerUserId: string;
    scheduleKind: "at" | "every" | "cron";
}, Promise<void>>;
export declare const patchJob: import("convex/server").RegisteredMutation<"public", {
    unset?: string[] | undefined;
    jobId: string;
    ownerUserId: string;
    patch: any;
}, Promise<{
    _id: import("convex/values").GenericId<"cronJobs">;
    _creationTime: number;
    agentId?: string | undefined;
    description?: string | undefined;
    sessionKey?: string | undefined;
    wakeMode?: string | undefined;
    delivery?: ArrayBuffer | undefined;
    failureAlert?: any;
    deleteAfterRun?: boolean | undefined;
    createdByChannelId?: string | undefined;
    createdByConversationId?: string | undefined;
    createdByAccountId?: string | undefined;
    scheduleExpr?: string | undefined;
    scheduleTz?: string | undefined;
    scheduleStaggerMs?: number | undefined;
    scheduleEveryMs?: number | undefined;
    scheduleAnchorMs?: number | undefined;
    scheduleAt?: number | undefined;
    stateNextRunAtMs?: number | undefined;
    stateLastRunAtMs?: number | undefined;
    stateRunningAtMs?: number | undefined;
    stateLastStatus?: string | undefined;
    stateLastError?: string | undefined;
    stateScheduleErrorCount?: number | undefined;
    stateConsecutiveErrorCount?: number | undefined;
    stateLastFailureAlertAtMs?: number | undefined;
    stateLastDelivered?: boolean | undefined;
    stateLastDeliveryStatus?: string | undefined;
    stateLastDeliveryError?: string | undefined;
    name: string;
    enabled: boolean;
    sessionTarget: string;
    payload: ArrayBuffer;
    jobId: string;
    updatedAtMs: number;
    createdByKind: "owner" | "channel" | "legacy";
    ownerUserId: string;
    scheduleKind: "at" | "every" | "cron";
    createdAtMs: number;
} | null>>;
export declare const deleteJob: import("convex/server").RegisteredMutation<"public", {
    jobId: string;
    ownerUserId: string;
}, Promise<boolean>>;
export declare const markRunning: import("convex/server").RegisteredMutation<"public", {
    jobId: string;
    ownerUserId: string;
    runningAtMs: number;
}, Promise<boolean>>;
export declare const appendRunLog: import("convex/server").RegisteredMutation<"public", {
    error?: string | undefined;
    provider?: string | undefined;
    delivered?: boolean | undefined;
    sessionKey?: string | undefined;
    nextRunAtMs?: number | undefined;
    model?: string | undefined;
    sessionId?: string | undefined;
    runAtMs?: number | undefined;
    summary?: ArrayBuffer | undefined;
    durationMs?: number | undefined;
    deliveryStatus?: string | undefined;
    deliveryError?: string | undefined;
    usageInput?: number | undefined;
    usageOutput?: number | undefined;
    usageCacheRead?: number | undefined;
    usageCacheWrite?: number | undefined;
    usageTotalTokens?: number | undefined;
    usageCostUsd?: number | undefined;
    jobId: string;
    status: "error" | "ok" | "skipped";
    ts: number;
    ownerUserId: string;
}, Promise<void>>;
export declare const listRunLog: import("convex/server").RegisteredQuery<"public", {
    limit?: number | undefined;
    jobId: string;
    ownerUserId: string;
}, Promise<{
    _id: import("convex/values").GenericId<"cronRuns">;
    _creationTime: number;
    error?: string | undefined;
    provider?: string | undefined;
    delivered?: boolean | undefined;
    sessionKey?: string | undefined;
    nextRunAtMs?: number | undefined;
    model?: string | undefined;
    sessionId?: string | undefined;
    runAtMs?: number | undefined;
    summary?: ArrayBuffer | undefined;
    durationMs?: number | undefined;
    deliveryStatus?: string | undefined;
    deliveryError?: string | undefined;
    usageInput?: number | undefined;
    usageOutput?: number | undefined;
    usageCacheRead?: number | undefined;
    usageCacheWrite?: number | undefined;
    usageTotalTokens?: number | undefined;
    usageCostUsd?: number | undefined;
    jobId: string;
    status: "error" | "ok" | "skipped";
    ts: number;
    ownerUserId: string;
}[]>>;
//# sourceMappingURL=cron.d.ts.map