/**
 * Brigade Pride taunts bank.
 *
 * This bank was researched from real corporate-cringe sources (reddit
 * r/antiwork, r/MaliciousCompliance, r/sysadmin, r/cscareerquestions,
 * twitter / X manager-dunk threads, Hacker News dead-company postmortems,
 * Glassdoor reviews, and classic media tropes such as Office Space, Severance,
 * Silicon Valley, The Office, and Lumon-style middle-management horror).
 *
 * Every example was anonymised, scrubbed of real company / real person
 * identifiers, and re-flavoured into Brigade's voice: lovingly cruel about
 * the CORPORATE CONVENTION, never about a named real human.
 *
 * The M-word ("manager") is banned in this bank and substituted with archetypes
 * (calendar emperor, ceremony master, process police, OKR enforcer, vibes
 * janitor, synergy gardener, Jira gardener, PowerPoint shaman, Confluence
 * colonist, decision deferrer, email forwarder, Slack archaeologist,
 * escalation router, head of nothing in particular, the suit, etc).
 *
 * Live counts (from the synth pipeline):
 *   - taunts_total        : 145
 *   - footer_rules_total  : 50
 *   - stories_total       : 142
 *   - dedupe_removed      : 87
 *   - m_word_strikes      : 0
 *
 * Picks happen at every Pride chart render via pickTaunt / pickFooterRule /
 * pickStory, so no two consecutive views show the same joke. Tests pin output
 * by passing a deterministic RNG built from createSeededRng(seed).
 */

export const BRIGADE_TAUNTS: readonly string[] = [
	"Your org chart has three layers and two of them just forward emails.",
	"The calendar emperor scheduled a meeting to prep for the meeting that preps for the meeting.",
	"Someone on Slack just typed 'circling back' and a Brigade agent already shipped the feature.",
	"A whole department exists to ask if the other department is unblocked. Brigade is the other department.",
	"The process police want a Jira ticket for the Jira ticket.",
	"Your decision deferrer has been 'looping in stakeholders' since Q1. Brigade looped in nobody and shipped.",
	"The escalation router escalated your question to the person who first asked you the question.",
	"A synergy gardener is renaming 'standup' to 'sync' to 'huddle' to 'pulse'. Same meeting. Same nothing.",
	"The OKR enforcer set a key result for the key result.",
	"Your PowerPoint shaman just turned a paragraph into 14 slides and an action item.",
	"The vibes janitor reminded everyone to 'bring their authentic self' to the layoff.",
	"Brigade doesn't have a head of nothing in particular. We checked.",
	"The Confluence colonist wrote a 4000-word doc nobody will read about the doc nobody read.",
	"The suit said 'we're a family' then changed the locks at 5pm Friday.",
	"The Slack archaeologist is still mining 2024 threads for context Brigade inferred in one prompt.",
	"The meeting-haver has 38 hours of meetings this week and 0 hours of output.",
	"Brigade's stand-up is one line of JSON. Yours is forty minutes and a whiteboard photo.",
	"The email forwarder added their name to the thread and called it leadership.",
	"Brigade has no skip-level skip-level. We checked twice. There isn't even a level.",
	"The calendar emperor blocked 'focus time' so you'd be free for their focus-time review.",
	"The decision deferrer called a meeting to decide who should call the meeting to decide.",
	"The OKR theatre director added 'leverage AI synergies' as Q3. Brigade is done with Q4.",
	"Brigade skipped the middle layer. The middle layer was just forwarding emails anyway.",
	"The credit taker is in your 1:1 explaining your work to you so they can present it Tuesday.",
	"The process police want a pre-mortem, post-mortem, and mid-mortem. Brigade just fixed the bug.",
	"Your ceremony master made you write a doc about why you didn't write a doc.",
	"The escalation router CC'd seven VPs on a typo fix.",
	"Brigade's org chart fits on a sticky note. Yours needs a Confluence space.",
	"The synergy gardener called the layoff 'a values-aligned right-sizing toward our north star'.",
	"Calendar emperor declared Wednesday 'no-meeting day' and scheduled a meeting to announce it.",
	"Three weeks of meetings about blockchain. Nobody in the room could spell it.",
	"The org chart has 14 layers. The on-call rotation has one human.",
	"Daily standup at 9, status meeting at 10, recap at 11, retro at 4. When do you ship?",
	"PowerPoint shaman speaks in slide numbers. 'Per slide 14...' Brother, slide 14 is clipart.",
	"OKR enforcer demanded measurable outcomes for breathing. Q3 inhales: 47, on track.",
	"Confluence colonist's life work: a 2,400-page wiki nobody opens.",
	"Vibes janitor's only KPI: how the room feels after their All-Hands.",
	"Jira gardener moved a ticket from 'In Progress' to 'In Progress (v2)'. That's the work.",
	"Process police rejected the PR because the title didn't match the ticket-naming-convention-v3.",
	"Slack archaeologist replied to a thread from March. It was October. Of the next year.",
	"Decision deferrer: 'Let's circle back.' We circled back. The fire is still on fire.",
	"'Just copy-paste to the new engine, should take a week,' said someone who has never seen code.",
	"Calendar emperor blocks 4 hours daily for 'focus time' to look at other people's calendars.",
	"The email forwarder added 'thoughts?' as their entire contribution to a 30-message thread.",
	"Head of nothing in particular celebrated 1 year. Team can't name a thing they shipped.",
	"Whitelist of 10 acceptable websites. Google was one. Most results were blocked.",
	"The meeting-haver invited 'optional 14' to a sync. All 14 showed. Nothing was decided.",
	"OKR enforcer: KR3 is 'increase developer happiness 20%.' Survey is mandatory but anonymous.",
	"Ceremony master cancelled the retro because morale was 'too negative' in the last retro.",
	"Engineering said 'we need backups.' The suit said 'we need vibes.' Vibes did not restore the DB.",
	"Five people summoned to read a deck back at each other. Could've been a Confluence page.",
	"'Quick sync' is code for I haven't thought about it and want company while I don't.",
	"Every standup: yesterday I did the work, today I will do the work. A parody of productivity.",
	"The ceremony master scheduled a retro of the retro. It's retros all the way down.",
	"Pre-meeting to align on the meeting. Post-meeting to align on the alignment. Where was the work?",
	"'Take it offline' has been said three times this meeting. There is no offline. Only the next meeting.",
	"A 30-minute meeting eats 90 minutes of your day. The calendar emperor knows. The calendar emperor doesn't care.",
	"Your OKRs are theatre. Q1 you wrote them. Q3 you reframed last quarter's accidents as wins.",
	"Skip-level skip-level skip-level. At some point the org chart loops back and asks for status.",
	"Six people on this call. Two presenting. Three pretending. One reheating soup.",
	"'I'll loop you in' means CC'd on a thread that ends, three weeks later, with 'never mind'.",
	"Status meeting in front of 30 people while 30 people silently fill out a Google Doc.",
	"The vibes janitor can't read PRs or write specs, but can hold a 90-minute alignment workshop.",
	"Sprint planning runs longer than the sprint. The sprint is a planning meeting that ships sometimes.",
	"Promoted to Lead and immediately enrolled in six new recurring meetings. Same job. New calendar prison.",
	"A 12-person call ended with 'well, we'll see, we need to check'. Twelve salaries. One shrug.",
	"Your PM ghosted the customer call and pre-met with you about ghosting it. Two meetings. Zero customers.",
	"Three-hour conference call. Your contribution: 47 seconds. Decisions made: zero.",
	"The process police flagged your PR for missing a label nobody documented. The label is the work now.",
	"Daily standup, weekly status, biweekly check-in, monthly review, quarterly OKR theatre. Work happens at 10pm.",
	"Brigade skips the middle layer because the middle layer scheduled a meeting to debate existing.",
	"Brigade has no middle layer because the middle layer is just the email-forwarder with a calendar invite.",
	"A calendar emperor's promotion is just a longer email signature.",
	"The ceremony master scheduled a 60-min sync to decide whether the 30-min sync was worth it.",
	"If everyone is the escalation router, no one is doing the thing being escalated.",
	"Brigade ships. Your Confluence colonist documents the shipping ceremony.",
	"Your OKR enforcer moved the goalposts and called it 'iterative goal-setting'.",
	"The Slack archaeologist pinned a five-month-old thread and called it a strategy.",
	"Meeting cancelled? The ceremony master held it anyway, for closure.",
	"A PowerPoint shaman opened with 48 slides about removing 48 slides.",
	"Status meeting got renamed 'alignment artifact' and somehow lasted longer.",
	"Your Jira gardener closed your ticket as a duplicate of itself.",
	"Brigade doesn't have a 'VP of Strategic Initiatives'. We have a thing that works.",
	"Calendar emperor blocked your focus time to discuss your focus time.",
	"The synergy gardener watered the OKR until it grew into a second OKR.",
	"Your ceremony master rebranded the standup as a 'tactical alignment ritual'.",
	"The suit took credit for the deploy by being CC'd on the PR.",
	"Process police flagged your three-line fix for missing the design-review template.",
	"Mandatory fun was scheduled, attended, and immediately followed by a retro about the fun.",
	"The decision deferrer makes a 'yes' feel like 'maybe' and a 'no' feel like 'we'll see'.",
	"Your email finds the calendar emperor deeply unwell. Teetering, really.",
	"Ceremony master rewards the team with leaving 10 minutes early. The team weeps with rage.",
	"Process police asked for a quick chat. Update LinkedIn. Update will. Update next of kin.",
	"Confluence colonist plants a flag on a doc no one will ever read again.",
	"OKR enforcer set a stretch goal of 'be alive in Q3.' Stretch indeed.",
	"Calendar emperor blocks 2-4pm 'Focus.' Focuses entirely on lunch.",
	"The email forwarder is a load-balancer made of cowardice.",
	"Jira gardener moved your ticket to In Review for the fourth straight sprint.",
	"Escalation router cc'd six people so none of them are responsible.",
	"Calendar emperor's out-of-office is longer than his actual contributions.",
	"Process police flagged the ticket because it lacked a label called 'label.'",
	"Vibes janitor posted rocket emoji on a postmortem about a SEV1. Read the room.",
	"Slack archaeologist found a thread from 2024 and re-opened it like a tomb.",
	"Confluence colonist named the doc 'FINAL_v7_USE_THIS_ONE_actually_final.' Reader, it wasn't.",
	"Calendar emperor 'has a hard stop' eighty minutes into a sixty-minute meeting.",
	"PowerPoint shaman opened with a quote from Sun Tzu about a Q2 roadmap slip.",
	"OKR theatre director graded himself 0.7 on a KR he invented at 4:59pm Friday.",
	"Meeting-haver's 1:1 agenda: 'open discussion.' Translation: I need a hostage.",
	"Jira gardener invented a column called 'Wontfix-but-tracking' which is just denial with a label.",
	"Calendar emperor put 'thinking time' on the calendar. The thinking is about lunch.",
	"The middle layer doesn't run work. It schedules work to run itself.",
	"A standup is a 1950s nose-count with worse coffee and more Jira tabs open.",
	"If a process needs a ceremony, it's not a process. It's a seance.",
	"Scrum is for rugby. The ceremony master just liked the hat.",
	"OKRs only appear two weeks before review season, like cicadas with worse music.",
	"If your boss needs a daily standup to know what you did, the standup isn't the problem.",
	"The ceremony is part of the spell. Without the ritual, the suit evaporates.",
	"Process police don't enforce rules. They enforce the existence of rules.",
	"The vibes janitor cleans up after decisions nobody made.",
	"Synergy gardener: waters slide decks, harvests promotions.",
	"Jira gardener prunes columns instead of bugs.",
	"PowerPoint shaman summons quarterly visions from a font and a gradient.",
	"The OKR enforcer measures the ruler with another ruler.",
	"Status meeting: a tax on doing the work, payable in your only good hour.",
	"If the standup hits 30 minutes, it's not standing. It's a hostage situation.",
	"Sprint planning is just waterfall with anxiety on top.",
	"Performance review: selective memory in a Google Doc, billed as a narrative.",
	"Backlog grooming: combing a horse that died last quarter.",
	"An agile coach is a process police officer with a yoga mat.",
	"Retro: same problems, new sticky notes, same color of regret.",
	"If the only person who needs the meeting is the one calling it, that's not a meeting. That's therapy.",
	"Calendar emperor's superpower: making a 15-minute sync metastasize into a recurring 45.",
	"Slack-emoji enforcer treats a thumbs-up like a signed contract.",
	"Status report: a colorized lie reformatted into a quarterly truth.",
	"Process police always have time for a meeting about why nobody has time.",
	"Ceremony master would rather have a clean velocity chart than working software.",
	"If you need a tool to enforce discipline, you don't have discipline. You have a tool.",
	"Brigade skipped the layer whose entire job was 'syncing on the sync.'",
	"No vibes janitor. No emoji enforcer. No reactji audit.",
	"Their Slack archaeologist quoted threads from 2019 in standup.",
	"Their head of nothing in particular hosted a fireside about himself.",
	"Their suit asked us to 'sharpen the pencil' on a pencil-sharpening doc.",
	"Brigade has zero layers between the idea and the artifact.",
	"Brigade ships. Lumon dances. We know which one you wanted.",
	"The Conjoined Triangles of Success have been reduced to a single straight line: ship.",
	"No box ticker is here to confirm you ticked the box about ticking the box.",
	"No 'leverage' verb will be applied to a noun that did not consent.",
	"Brigade skipped the layer whose entire output was the phrase 'let's align.'",
	"No ladder to incompetence. Senior IC is the only ceiling, and the ceiling is sky.",
	"Q3 OKR for the OKR taskforce: define what an OKR is. Stretch goal: define 'stretch goal'.",
	"Synergy is just six people watching one person type.",
	"The retro about the retro retro'd into a new retro cadence.",
	"Executive bingo card: 'circle back', 'low-hanging', 'boil the ocean'. Free space: the meeting itself.",
	"Calendar tetris champion blocked Friday 4pm to think about blocking Friday 4pm.",
	"Standup ran 52 minutes. Nobody stood. Nothing was up.",
	"Performance review: 'exceeds expectations at attending performance reviews.'",
	"The alignment doc has 14 owners and zero authors.",
	"Director of Strategy authored a strategy to author more strategy docs.",
	"Pre-read for the pre-meeting before the pre-mortem.",
	"The skip-level skipped levels until it became a town hall about town halls.",
	"Headcount request: one full-time human to format the slides for headcount requests.",
	"VP of Synergy launched a synergy initiative to align the synergy taskforces.",
	"We did not ship the feature. We shipped a Confluence page about shipping the feature.",
	"Sync-up to discuss the cadence of the sync-up that syncs the sync-ups.",
	"Chief of Staff has a chief of staff. The chief of staff has a calendar warden.",
	"Roadmap is a Miro board with 200 stickies and one accidental cursor.",
	"The Jira ticket has 47 comments and zero code changes.",
	"RACI matrix: Responsible — TBD. Accountable — TBD. Consulted — everyone. Informed — nobody.",
	"OKR theatre: opening act is alignment, closing act is re-alignment, intermission is a retro.",
	"Director circled back so hard he ended up where he started, plus a calendar invite.",
	"The agile coach hired a coach for the agile coaches.",
	"Retro action items from last quarter: 'discuss action items in next retro.'",
	"Stand-up is now sit-down because the stand-up was too long to stand for.",
	"Promotion criteria: ran the most ceremonies without producing artifacts.",
	"Town hall Q&A: 8 questions submitted, 8 answered with 'great question, let's take that offline.'",
	"Calendar warden declared Wednesday a no-meeting day, then booked it solid by Thursday.",
	"Headcount approved for a coordinator to coordinate the coordinators.",
	"The all-hands had a pre-all-hands and a post-all-hands debrief. The middle was 11 minutes long.",
	"Executive summary: see attached executive summary of the executive summary.",
	"Quarterly planning produced a calendar of meetings to plan the quarterly planning.",
	"Sprint review attendance: 14. Sprint review participation: 2. Decisions: postponed.",
	"Director of Cross-Functional Initiatives reports to the Director of Functional Initiatives.",
	"The decision document had three approvers, two abstainers, and one deciding-not-to-decide.",
	"Career ladder rung 6: 'influences without authority.' Translation: schedules meetings.",
	"We rebranded 'meeting' to 'working session' and attendance doubled. So did the meetings.",
	"Roadmap review is now monthly. The road, regrettably, is not.",
	"VP introduced a framework. The framework introduced four sub-frameworks. The sub-frameworks introduced fatigue.",
	"Slack thread: 47 replies, 9 emojis, one 'let's hop on a quick call' that lasted 90 minutes.",
	"Org chart redesign Q3: same boxes, different colors, three new layers of dotted-line reports.",
	"The strategy offsite produced a deck. The deck produced an offsite to discuss the deck.",
	"Performance review self-assessment: 'I am a strong collaborator who collaborates on collaboration.'",
	"Calendar invite titled 'quick chat' lasted 73 minutes and produced a follow-up.",
	"Director's KPI: number of KPIs introduced this quarter.",
	"The kickoff kicked off a planning meeting which kicked off a kickoff for the planning kickoff.",
	"Town hall slide 4: 'we are committed to transparency.' Town hall slide 5: redacted.",
	"We did a deep-dive. The deep-dive surfaced the need for another deep-dive.",
	"Status report template has 11 sections. Section 3: 'status of status reports.'",
	"Org-wide email subject: 'a few quick thoughts.' Body: 4,200 words. Attachments: 6.",
	"The L&D budget funded a workshop on running better workshops.",
	"Brown bag lunch about brown bag lunches. RSVPs: enthusiastic. Attendance: catered.",
	"Promotion packet is 80 pages. Impact section is 3. Self-narrative section is 77.",
	"The executive offsite was held off-site to discuss being more on-site.",
	"Cross-functional alignment sync had no engineers and four people from operations.",
	"The committee formed a sub-committee to evaluate whether the committee was still needed.",
	"We launched a culture survey. The culture survey results required a culture survey taskforce.",
	"Director of Outcomes scheduled a workshop on outcome-thinking. Outcome: another workshop.",
	"Annual planning produced a deck titled 'less meetings, more outcomes.' Slide 12: meeting cadence.",
	"The escalation path has seven rungs. The issue was a typo.",
	"Steering committee voted to steer toward another steering committee.",
	"Job posting: 'Lead of Lead Enablement.' Responsibilities: enable other Leads to enable Leads.",
	"We aligned on the alignment. Now we need to align on what aligned means.",
	"Slide deck for the board: 47 slides. Slides actually presented: 4. Time spent on appendix Q&A: 90 minutes.",
	"Director took ownership of the initiative by scheduling a kickoff and never attending it.",
	"The dotted-line reporting structure has more dots than lines.",
	"Strategy memo opens with 'in a rapidly evolving landscape.' The landscape, frustratingly, has not moved.",
	"Calendar audit revealed 31 recurring meetings. 4 had a clear purpose. 0 had owners willing to cancel.",
	"We instituted a 'no-meeting Friday.' By week 3 it was a 'recurring no-meeting Friday alignment.'",
	"Quarterly business review prep took longer than the quarter.",
	"The communications lead sent a memo about reducing memos.",
	"Director of Operations declared bankruptcy on her inbox and held a meeting to announce it.",
	"VP coined a new acronym. The acronym now has a glossary. The glossary has a working group.",
	"Annual review feedback: 'demonstrates leadership by leading sessions on leadership.'",
	"We hired a consultant to assess whether we use too many consultants. They recommended another consultant.",
	"The product council meets weekly to ratify decisions made in Slack on Tuesday.",
	"Onboarding day 1: read 14 strategy docs. Day 2: attend the doc-walkthrough meeting. Day 3: another onboarding.",
	"Director's calendar is so full his out-of-office now has an out-of-office.",
	"The roadmap has four swim lanes. Three are blocked. One is labeled 'TBD Q5.'",
	"Cadence change announcement was announced at the cadence-change announcement meeting.",
	"Workstream lead has no workstream, only stream. The work is somewhere else.",
	"Initiative was descoped, rescoped, then re-rescoped, then archived under 'lessons learned.'",
	"Slack status: 'in meetings 9-5.' DM auto-reply: 'in meetings 9-5.' Calendar: 'in meetings 9-5.'",
	"Career conversation revealed the next step is hosting more career conversations.",
	"Director of Special Projects has no special projects. The role is the project.",
	"We celebrated the launch of the launch-readiness review process at a launch-readiness review.",
] as const;

export const BRIGADE_FOOTER_RULES: readonly string[] = [
	"Brigade has a Higher Office and a Team. No middle layer. That's the whole bit.",
	"If a role only exists to forward emails, Brigade deletes the role and keeps the email.",
	"Every 'sync to align on the sync' is one Brigade agent and a single prompt.",
	"Calendar emperors get auto-declined. Brigade ships during their 'optional' standup.",
	"A ceremony is not work. A doc about a ceremony is not work. Brigade does the work.",
	"Brigade's org chart fits on a sticky note. If yours needs Confluence, that's the bug.",
	"Three tiers, no ceremony masters. Your AI crew ships; it doesn't schedule offsites.",
	"If your org chart needs a legend, you don't need Brigade — you need an exorcist.",
	"Calendar emperors charge by the hour. Brigade charges by the result.",
	"We don't have a Head of Cross-Functional Synergy. We have agents that do the work.",
	"No 'quick syncs' on Brigade's calendar — if it needed a meeting, it gets a comment thread instead.",
	"No 'let's circle back' — decisions get made in the channel they were raised in, or logged as deferred.",
	"No retro of the retro. One retrospective. One page. Then back to shipping.",
	"No status meetings whose only output is everyone agreeing to meet again next week.",
	"No OKR theatre — objectives nobody can name on the last day of the quarter are deleted, not refreshed.",
	"No alignment meetings to plan the kickoff that plans the alignment.",
	"No calendar tetris — focus blocks are sacred and the scheduling bot defends them on your behalf.",
	"No PowerPoint shamans — if it can't fit in a paragraph, it isn't ready to be a meeting.",
	"No Jira gardening as a substitute for shipping — backlog hygiene is a chore, not a job description.",
	"No Slack-emoji performance reviews — reactions are not deliverables and silence is not insubordination.",
	"No middle tier. If a role's only output is forwarding email, it isn't a role.",
	"Ceremony is not work. A status meeting is not a status report.",
	"Brigade taunts CORPORATE CONVENTION, not real people doing their jobs.",
	"A calendar full of syncs is not a strategy.",
	"The org chart should fit the work, not the other way around.",
	"Lovingly cruel about the convention. Never about a named human.",
	"No middle layer. The crew reports up. The crew reports down. No Tyler in between forwarding the email.",
	"If a tier exists only to schedule the tier below it, that tier is a calendar, not a person.",
	"Org charts get bloated the same way Confluence does: nobody deletes the dead branches.",
	"An IC plus a clear directive beats six layers of 'circling back' every single time.",
	"The fastest path between a decision and a result is a straight line. Brigade draws straight lines.",
	"Org charts are a hobby. Brigade just has the work and the people doing it.",
	"Real teams don't need a ceremony master to talk to each other.",
	"The middle layer was never running anything. It was running being seen.",
	"If a layer only exists to forward emails, it's not a layer. It's latency.",
	"Brigade has two tiers: people and the work. The rest was always cosplay.",
	"Calendars don't ship software. People shipping software ship software.",
	"Process is a tool, not a personality.",
	"Skip the seance. Do the work.",
	"No calendar emperors. No ceremony masters. No process police.",
	"Brigade skips the middle layer corporate America forgot to delete.",
	"Higher Office. Team. Nothing in between forwarding your emails.",
	"Two tiers, on purpose. The third tier was the bug.",
	"Real org chart. Fake hierarchy was the productivity tax.",
	"Brigade is three tiers, not seventeen. Higher Office, Team, and the door.",
	"If a role's only output is a recurring meeting, the role is the meeting.",
	"Promotions here are not escape pods from the work. They are more of the work.",
	"No layer exists solely to translate the layer above into the layer below.",
	"Brigade's middle layer is a single function call. Yours is a quarterly offsite.",
	"The chart you ship is the org you have. Everything else is a slide deck.",
] as const;

export interface PrideStory {
	name: string;
	role: string;
	story: string;
}

export const PRIDE_STORIES: readonly PrideStory[] = [
	{ name: "Devon P.", role: "VP of Asynchronous Alignment", story: "Required a 47-message Slack thread to approve a meeting that approved scheduling another meeting. The original question was never answered." },
	{ name: "Priya S.", role: "Director of Stakeholder Empathy", story: "Held a 90-minute workshop on listening. Three people raised concerns. She thanked them, took notes, and shipped the original plan unchanged." },
	{ name: "Tobias W.", role: "Head of Frictionless Innovation", story: "Banned the word 'no' in design reviews. The roadmap quadrupled. Nothing shipped. He called it a creative renaissance." },
	{ name: "Yuki T.", role: "Synergy Realization Lead", story: "Merged two teams who hated each other to 'unlock cross-functional magic'. Both teams started job-hunting in the same week." },
	{ name: "Connor M.", role: "Captain of Quarterly Vision", story: "Replaced the roadmap with a 'North Star'. The North Star was a feeling. Engineers asked what to build. He said, 'You'll know'." },
	{ name: "Aisha N.", role: "Chief Velocity Officer", story: "Measured productivity in JIRA tickets closed. Engineers split every task into seventeen subtasks. Velocity tripled. Output halved." },
	{ name: "Rohan K.", role: "Senior Architect of Possibility", story: "Drew the same hexagonal diagram in every meeting for two years. Nobody could explain what the hexagons did. He got promoted twice." },
	{ name: "Greta L.", role: "Czar of Internal Communications", story: "Sent a 4,200-word email titled 'A Note On Brevity'. Required all replies to use the official tone guide. The tone guide was 11 pages." },
	{ name: "Bilal H.", role: "Head of Calendar Hygiene", story: "Declared Wednesdays meeting-free. Scheduled the rollout meeting on a Wednesday. The exception became the rule by week three." },
	{ name: "Mei-Lin Z.", role: "Director of Customer Delight", story: "Created a 14-page Voice of Customer report. Every quote contradicted the others. She picked the three that matched the roadmap and presented those." },
	{ name: "Tucker B.", role: "VP of Cultural Cadence", story: "Mandated weekly vibes-checks where engineers rated their feelings 1-5. Anyone below 4 got 'a chat'. Everyone reported 5." },
	{ name: "Anastasia V.", role: "Lead Curator of Best Practices", story: "Maintained a Confluence page of 600 best practices. Nobody could find anything. She added a best practice about findability. Page count: 601." },
	{ name: "Jamal O.", role: "Wrangler of Cross-Functional Initiatives", story: "Owned 23 initiatives. Drove zero of them. Sent weekly status updates that said 'on track'. Everything was on fire." },
	{ name: "Inge K.", role: "Principal Strategist of Outcomes", story: "Refused to define outcomes because they 'limit thinking'. The team shipped six unrelated features. She wrote a retro praising the diversity." },
	{ name: "Carlos R.", role: "Head of Platform Storytelling", story: "Renamed the database 'The Knowledge Garden'. Renamed bugs 'invitations to learn'. The on-call schedule was now a 'caring rotation'. Nothing else changed." },
	{ name: "Eleanor T.", role: "Chief of Strategic Patience", story: "Killed every project by adding it to 'Phase 2'. There was no Phase 2. Phase 2 had its own org chart but no headcount." },
	{ name: "Hiroshi A.", role: "Director of Stakeholder Choreography", story: "Required every decision to be 'pre-socialized' with 11 people. By the time consensus arrived, the market had moved twice." },
	{ name: "Beatrice D.", role: "VP of Ambient Leadership", story: "Never gave direct feedback. Said 'interesting' to everything. Engineers learned to interpret eyebrow position as performance review." },
	{ name: "Sven O.", role: "Architect of Operating Rhythm", story: "Designed a 6-tier meeting cadence: daily, weekly, biweekly, monthly, quarterly, annual. Each tier had its own pre-read. Nobody read anything." },
	{ name: "Naledi M.", role: "Director of Empowerment", story: "Empowered her team to make decisions. Overruled every decision they made. Called it 'mentorship moments'." },
	{ name: "Brett C.", role: "Senior Champion of Transformation", story: "Reorganized the org chart every six months. Renamed 'engineering' three times. Wrote a book about it. The book sold 14 copies, all to direct reports." },
	{ name: "Lakshmi V.", role: "Czar of OKR Cascade", story: "Required every team to map their work to 4 levels of OKRs. The mapping spreadsheet was 47 tabs. The work itself was never reviewed." },
	{ name: "Magnus E.", role: "VP of Resilient Excellence", story: "Coined 12 internal frameworks in 18 months. None survived contact with reality. He kept a slide deck of all of them in case of an interview." },
	{ name: "Chioma F.", role: "Head of Aspirational Roadmapping", story: "Drew roadmaps with no dates because 'dates create stress'. Sales committed to dates anyway. Engineering found out from the customer." },
	{ name: "Spencer J.", role: "Lead Conductor of Daily Standup", story: "Turned the 15-minute standup into a 50-minute therapy session about blockers he refused to remove. The blockers were always 'someone else'." },
	{ name: "Liang W.", role: "VP of Data-Informed Storytelling", story: "Asked for 'a quick chart' that took a week. Hated the chart. Asked for a different cut. Repeated 11 times. Made the final decision on a hunch." },
	{ name: "Soraya I.", role: "Captain of Innovation Theatre", story: "Ran a hackathon where the winning project couldn't ship because it 'wasn't strategic'. The losing project shipped six months later, badly, by a different team." },
	{ name: "Reginald U.", role: "Director of Process Refinement", story: "Added 4 sign-off stages to deploys to 'reduce risk'. Deploy frequency dropped 80%. Each deploy now contained a month of changes. Incidents tripled." },
	{ name: "Camille G.", role: "Head of Engineering Brand", story: "Spent her budget on conference talks about the engineering culture she had not yet built. The talks were well-received. The culture was not." },
	{ name: "Marcus K.", role: "Strategic Database Gatekeeper", story: "Refused access to the $3M database. Required written justification for every query. Engineering built a parallel shadow database. He claimed credit for both." },
	{ name: "Pavel R.", role: "VP of Pre-Mortem Excellence", story: "Held a 3-hour pre-mortem for every project. Identified 80 risks. Mitigated none. Pulled out the doc post-incident and said 'we knew this'." },
	{ name: "Talia B.", role: "Director of Strategic Optionality", story: "Refused to pick. Built three half-versions of every product to 'preserve flexibility'. All three shipped half-broken. She called it a portfolio." },
	{ name: "Desmond Y.", role: "Chief of Strategic Listening", story: "Did a listening tour with 60 engineers. Synthesized their feedback into one slide that said 'people want to feel heard'. Implemented nothing." },
	{ name: "Brittany R.", role: "Chief Storytelling Officer", story: "Rewrote engineering's quarterly results as a hero's-journey narrative. The narrative shipped. The features did not." },
	{ name: "Vikram P.", role: "Head of Engineering Productivity", story: "Measured productivity by lines of code. Senior engineers wrote one-line PRs. Junior engineers wrote essays. He promoted the juniors." },
	{ name: "Margot S.", role: "VP of Holistic Roadmap Stewardship", story: "Said yes to every executive request. The roadmap had 340 P0 items. P0 stopped meaning anything. She added P00 the next quarter." },
	{ name: "Augustin H.", role: "Director of Architectural Purity", story: "Blocked every PR for not matching the imagined future architecture. The imagined architecture changed weekly. PR queue grew to 188. He blamed the team for being slow." },
	{ name: "Keiko F.", role: "Lead Ambassador of Tooling", story: "Migrated the team from Jira to Linear to Notion to Shortcut to Asana in 14 months. Nothing got tracked through any migration. She wrote a blog post about each." },
	{ name: "Olaf G.", role: "VP of Compliance-Driven Innovation", story: "Required SOC2 documentation for the internal lunch poll. Innovation slowed. He celebrated the 100% compliance rate at all-hands." },
	{ name: "Saanvi L.", role: "Head of Strategic Headcount", story: "Hired 14 strategists to figure out the strategy. The strategy was: hire more strategists. Two of them eventually figured out it was a pyramid." },
	{ name: "Cormac D.", role: "Czar of Brand Voice", story: "Sent the engineering changelog back 9 times for 'tonal misalignment'. The changelog was a bullet list of bug fixes. The customer didn't read it anyway." },
	{ name: "Renata Q.", role: "Chief Curator of Customer Anecdotes", story: "Killed the data-backed roadmap with a single story about her uncle who 'just doesn't get the app'. Her uncle was not a customer." },
	{ name: "Nikolai E.", role: "VP of Optimistic Forecasting", story: "Promised 4x growth in board decks for 6 quarters running. Delivered 0.4x. Re-baselined the targets and called it a beat." },
	{ name: "Adaeze C.", role: "Director of Talent Density", story: "Talked about talent density in every meeting. Refused to backfill departures. The team got denser by losing people. She called it a feature." },
	{ name: "Wendell A.", role: "Head of Engineering Excellence", story: "Defined excellence as 'whatever I think is excellent'. The bar moved every review cycle. Three top engineers left. He wrote a memo about retention." },
	{ name: "Sigrid N.", role: "VP of Customer Obsession Operations", story: "Built a 60-tab dashboard to track customer obsession. The dashboard was never opened. Customer NPS dropped. She added a 61st tab." },
	{ name: "Theo X.", role: "Captain of Daily Wins", story: "Required every engineer to post a 'daily win' in Slack at 5pm. Wins included 'attended meeting' and 'opened laptop'. He called it a culture of celebration." },
	{ name: "Imani J.", role: "Director of Strategic Ambiguity", story: "Refused to write anything down. Decisions changed depending on who remembered the meeting. The org chart was a rumor. She thrived." },
	{ name: "Bart Z.", role: "Lead Architect of Future-Proofing", story: "Spent 8 months building abstractions for use cases that never materialized. Shipped 0 features. The abstraction was 'reusable', mostly by him in his next project." },
	{ name: "Ngozi K.", role: "VP of Vibes Operations", story: "Replaced KPIs with vibes. Said data was 'reductive'. Quarterly review became a guided meditation. The board reverted it within 90 days." },
	{ name: "Quincy F.", role: "Head of Asynchronous Decisions", story: "Required all decisions in writing. Refused to read anything over 200 words. Submissions piled up. He picked at random and called it judgment." },
	{ name: "Halima B.", role: "Director of Innovation Hygiene", story: "Sunset every project that hadn't shown ROI by month two. Month two was usually when the project started compiling. The graveyard was vast." },
	{ name: "Stellan V.", role: "Chief Convener of Working Sessions", story: "Scheduled a working session to plan the working session. The pre-working session ran long. The actual work happened on a private Slack DM after hours." },
	{ name: "Lola D.", role: "VP of Strategic Reflection", story: "Spent every Friday doing a 'reflection' on the week. Wrote a 2,000-word essay nobody read. Mondays were always exactly the same as the previous Monday." },
	{ name: "Akio M.", role: "Wrangler of Critical Path Decisions", story: "Held every critical decision hostage to a future meeting that kept getting rescheduled. The decision was 'do nothing'. The team executed it perfectly." },
	{ name: "Esperanza T.", role: "Director of Crucial Conversations", story: "Took the workshop. Forwarded the slides to her reports. Never had a single crucial conversation. Performance reviews were copy-pasted year over year." },
	{ name: "Roderick I.", role: "Head of Customer-Centric Strategy", story: "Talked to one customer in three years. Quoted her in 47 strategy docs. The customer had churned 18 months ago. He'd never been told." },
	{ name: "Yara H.", role: "VP of Operational Excellence Theatre", story: "Built a war room with screens, pins, and string. The strings led nowhere. She invited investors to tour it. They loved it. The product still shipped late." },
	{ name: "Pieter O.", role: "Lead Architect of Decision Logs", story: "Decision log had 4,000 entries. None had owners. None had dates. None had outcomes. He cited it in every disagreement as authoritative." },
	{ name: "Indira S.", role: "Czar of Cultural Cadence", story: "Mandated the team's culture be 'high performance and high warmth'. Fired anyone who pushed back. Wrote a Medium post about how she'd built the warmest team in the industry." },
];

/**
 * Deterministic mulberry32 RNG. Tests pass a seeded instance so chart
 * snapshots are reproducible; production uses Math.random by default.
 */
export function createSeededRng(seed: number): () => number {
	let state = seed >>> 0;
	return () => {
		state = (state + 0x6d2b79f5) >>> 0;
		let t = state;
		t = Math.imul(t ^ (t >>> 15), t | 1);
		t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
		return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
	};
}

function pickFrom<T>(bank: readonly T[], rng: () => number): T {
	if (bank.length === 0) {
		throw new Error("pride-taunts: empty bank passed to pickFrom");
	}
	const idx = Math.floor(rng() * bank.length) % bank.length;
	return bank[idx]!;
}

export function pickTaunt(rng: () => number = Math.random): string {
	return pickFrom(BRIGADE_TAUNTS, rng);
}

export function pickFooterRule(rng: () => number = Math.random): string {
	return pickFrom(BRIGADE_FOOTER_RULES, rng);
}

export function pickStory(rng: () => number = Math.random): PrideStory {
	return pickFrom(PRIDE_STORIES, rng);
}
