#!/usr/bin/env node
// scripts/convex-dev.mjs
//
// Brigade local Convex orchestrator — fully air-gapped, zero cloud touch.
// Spawns the self-hosted convex-local-backend binary + serves the dashboard
// on 127.0.0.1:6791. Same path OSS users will use; no Convex account needed.
//
//   npm run convex:dev
//
// Persists state under F:\Brigade\.convex-data\:
//   identity.json                       — stable instance name + secret (do not commit)
//   admin-key.txt                       — derived admin key, written each run
//   convex_local_backend.sqlite3        — database file
//   storage/                            — Convex File Storage objects
//   logs/                               — backend stderr captures

import { spawn } from "node:child_process";
import { mkdirSync, existsSync, writeFileSync, readFileSync } from "node:fs";
import { randomBytes } from "node:crypto";
import { createServer } from "node:http";
import { readFile, stat } from "node:fs/promises";
import { extname, join, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const BIN_DIR = join(ROOT, "bin");
const DATA_DIR = join(ROOT, ".convex-data");
const DASHBOARD_DIR = join(BIN_DIR, "dashboard");
const BACKEND_BIN = join(BIN_DIR, process.platform === "win32" ? "convex-local-backend.exe" : "convex-local-backend");

const BACKEND_HOST = "127.0.0.1";
const BACKEND_PORT = 3210;
const SITE_PROXY_PORT = 3211;
const DASHBOARD_PORT = 6791;

const INSTANCE_NAME = "brigade-local";

// ---------------------------------------------------------------------------
// 1. Sanity checks
// ---------------------------------------------------------------------------
if (!existsSync(BACKEND_BIN)) {
  console.error(`✖ Backend binary not found: ${BACKEND_BIN}`);
  console.error(`  Run \`node scripts/install-convex.mjs\` to download it.`);
  process.exit(1);
}
if (!existsSync(DASHBOARD_DIR)) {
  console.error(`✖ Dashboard not found: ${DASHBOARD_DIR}`);
  console.error(`  Run \`node scripts/install-convex.mjs\` to download it.`);
  process.exit(1);
}

mkdirSync(DATA_DIR, { recursive: true });
mkdirSync(join(DATA_DIR, "storage"), { recursive: true });
mkdirSync(join(DATA_DIR, "logs"), { recursive: true });

// ---------------------------------------------------------------------------
// 2. Stable identity — generate once, persist forever
// ---------------------------------------------------------------------------
const IDENTITY_FILE = join(DATA_DIR, "identity.json");
let identity;
if (existsSync(IDENTITY_FILE)) {
  identity = JSON.parse(readFileSync(IDENTITY_FILE, "utf8"));
} else {
  identity = {
    instanceName: INSTANCE_NAME,
    instanceSecret: randomBytes(32).toString("hex"),
    createdAt: new Date().toISOString(),
  };
  writeFileSync(IDENTITY_FILE, JSON.stringify(identity, null, 2));
  console.log(`✓ Generated stable instance identity at ${IDENTITY_FILE}`);
}

// ---------------------------------------------------------------------------
// 3. Derive admin key via `keygen admin-key`
// ---------------------------------------------------------------------------
import { execSync } from "node:child_process";
const adminKey = execSync(
  `"${BACKEND_BIN}" keygen admin-key --instance-name "${identity.instanceName}" --instance-secret "${identity.instanceSecret}"`,
  { encoding: "utf8" }
).trim();
writeFileSync(join(DATA_DIR, "admin-key.txt"), adminKey);

// ---------------------------------------------------------------------------
// 4. Write .env.local for the Convex CLI + Brigade gateway
// ---------------------------------------------------------------------------
const envContent = [
  `# Auto-generated by scripts/convex-dev.mjs — do not commit`,
  `CONVEX_SELF_HOSTED_URL=http://${BACKEND_HOST}:${BACKEND_PORT}`,
  `CONVEX_SELF_HOSTED_ADMIN_KEY=${adminKey}`,
  `# Also expose plain CONVEX_URL for client code:`,
  `CONVEX_URL=http://${BACKEND_HOST}:${BACKEND_PORT}`,
  ``,
].join("\n");
writeFileSync(join(ROOT, ".env.local"), envContent);

// ---------------------------------------------------------------------------
// 5. Spawn the backend
// ---------------------------------------------------------------------------
const dbPath = join(DATA_DIR, "convex_local_backend.sqlite3");
const storagePath = join(DATA_DIR, "storage");

console.log(`\x1b[36m▌ Starting Convex local backend\x1b[0m`);
console.log(`\x1b[36m▌   backend  → http://${BACKEND_HOST}:${BACKEND_PORT}\x1b[0m`);
console.log(`\x1b[36m▌   site     → http://${BACKEND_HOST}:${SITE_PROXY_PORT}\x1b[0m`);
console.log(`\x1b[36m▌   db       → ${dbPath}\x1b[0m`);
console.log(`\x1b[36m▌   storage  → ${storagePath}\x1b[0m`);

const backend = spawn(BACKEND_BIN, [
  "--interface", BACKEND_HOST,
  "--port", String(BACKEND_PORT),
  "--site-proxy-port", String(SITE_PROXY_PORT),
  "--instance-name", identity.instanceName,
  "--instance-secret", identity.instanceSecret,
  "--local-storage", storagePath,
  "--do-not-require-ssl",
  dbPath,
], { stdio: ["ignore", "pipe", "pipe"] });

backend.stdout.on("data", (b) => process.stdout.write(`\x1b[90m[backend]\x1b[0m ${b}`));
backend.stderr.on("data", (b) => process.stderr.write(`\x1b[90m[backend]\x1b[0m ${b}`));
backend.on("exit", (code) => {
  console.error(`\x1b[31m[backend] exited with code ${code}\x1b[0m`);
  shutdown(code ?? 1);
});

// ---------------------------------------------------------------------------
// 5b. Push the current convex/ functions once the backend answers.
//
// The runbook always promised "boots the local backend + pushes convex/
// functions" — but nothing ever pushed, so the deployed bundle silently
// drifted from the code: every function added after the last manual push
// failed at runtime with "Could not find public function 'auth:readAuthFile'"
// while the gateway limped along half-broken. Pushing here (and via the
// standalone `npm run convex:push`) keeps backend and code in lockstep; the
// boot-time bundle-version gate in src/storage/boot.ts is the backstop.
// ---------------------------------------------------------------------------
async function pushFunctionsWhenReady() {
  const deadline = Date.now() + 60_000;
  let up = false;
  while (Date.now() < deadline && !shuttingDown) {
    try {
      const res = await fetch(`http://${BACKEND_HOST}:${BACKEND_PORT}/version`);
      if (res.ok) {
        up = true;
        break;
      }
    } catch {
      /* backend still starting */
    }
    await new Promise((r) => setTimeout(r, 500));
  }
  if (!up || shuttingDown) {
    if (!shuttingDown) {
      console.error(
        `\x1b[31m▌ Backend didn't answer within 60s — skipped the function push. Run \`npm run convex:push\` once it's up.\x1b[0m`,
      );
    }
    return;
  }
  console.log(`\x1b[36m▌ Pushing convex/ functions…\x1b[0m`);
  const push = spawn(process.execPath, [join(ROOT, "scripts", "convex-push.mjs")], {
    stdio: "inherit",
  });
  push.on("exit", (code) => {
    if (code === 0) {
      console.log(`\x1b[32m▌ Functions up to date.\x1b[0m`);
    } else {
      console.error(
        `\x1b[31m▌ Function push failed (code ${code}) — run \`npm run convex:push\` manually.\x1b[0m`,
      );
    }
  });
}
// NOTE: invoked at the BOTTOM of this file — it reads `shuttingDown`, which
// is declared in section 7 below; calling it here would hit the TDZ.

// ---------------------------------------------------------------------------
// 6. Spawn the static dashboard server on 127.0.0.1:6791
// ---------------------------------------------------------------------------
const MIME = {
  ".html": "text/html; charset=utf-8",
  ".css":  "text/css; charset=utf-8",
  ".js":   "application/javascript; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".svg":  "image/svg+xml",
  ".png":  "image/png",
  ".ico":  "image/x-icon",
  ".webmanifest": "application/manifest+json",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
};

const dashboardServer = createServer(async (req, res) => {
  try {
    let urlPath = decodeURIComponent((req.url ?? "/").split("?")[0]);
    if (urlPath === "/") urlPath = "/index.html";

    let filePath = join(DASHBOARD_DIR, urlPath);

    // SPA fallback — if the requested path has no extension and doesn't exist,
    // try $path.html, then fall back to index.html.
    let st;
    try { st = await stat(filePath); } catch {}
    if (!st || st.isDirectory()) {
      const candidates = [
        filePath + ".html",
        join(filePath, "index.html"),
        join(DASHBOARD_DIR, "index.html"),
      ];
      for (const c of candidates) {
        try {
          const s = await stat(c);
          if (s.isFile()) { filePath = c; st = s; break; }
        } catch {}
      }
    }
    if (!st || !st.isFile()) { res.writeHead(404); res.end("Not Found"); return; }

    const ext = extname(filePath).toLowerCase();
    const mime = MIME[ext] ?? "application/octet-stream";
    res.writeHead(200, { "content-type": mime, "cache-control": "no-store" });
    // Zero-click login. The dashboard's logged-in flag is in-memory React
    // state — sessionStorage alone never logs it in. The supported hook is
    // a postMessage handshake: on load the app broadcasts
    // "dashboard-credentials-request" to window.parent and auto-logs-in if
    // anything replies with {type:"dashboard-credentials", adminKey,
    // deploymentUrl, deploymentName}. The page is top-level here, so
    // window.parent === window and our injected listener can be that
    // responder. Localhost-only listener; same trust domain as the key
    // file itself. Respects Log Out: the dashboard records it as
    // sessionStorage adminKey = JSON '""' — we stay silent then so manual
    // re-login still works (fresh tabs have no marker and auto-login).
    if (ext === ".html") {
      const creds =
        `{type:"dashboard-credentials",adminKey:${JSON.stringify(adminKey)},` +
        `deploymentUrl:${JSON.stringify(`http://${BACKEND_HOST}:${BACKEND_PORT}`)},` +
        `deploymentName:${JSON.stringify(identity.instanceName)}}`;
      const html = (await readFile(filePath, "utf8")).replace(
        /<head>/i,
        `<head><script>(function(){try{` +
          `function loggedOut(){try{var k=sessionStorage.getItem("adminKey");` +
          `return k!==null&&JSON.parse(k||"null")===""}catch(e){return false}}` +
          `window.addEventListener("message",function(ev){` +
          `if(ev&&ev.data&&ev.data.type==="dashboard-credentials-request"&&!loggedOut()){` +
          `window.postMessage(${creds},"*");}});` +
          `}catch(e){}})();</script>`,
      );
      res.end(html);
      return;
    }
    res.end(await readFile(filePath));
  } catch (err) {
    res.writeHead(500);
    res.end(String(err));
  }
});

dashboardServer.listen(DASHBOARD_PORT, BACKEND_HOST, () => {
  const dashboardUrl = `http://${BACKEND_HOST}:${DASHBOARD_PORT}`;
  console.log(`\x1b[36m▌   dashboard → ${dashboardUrl}\x1b[0m`);
  console.log(`\x1b[33m▌ Add deployment in dashboard with:\x1b[0m`);
  console.log(`\x1b[33m▌   URL:        http://${BACKEND_HOST}:${BACKEND_PORT}\x1b[0m`);
  console.log(`\x1b[33m▌   Admin key:  (paste contents of .convex-data/admin-key.txt)\x1b[0m`);

  // Convenience: open the dashboard in the default browser and put the
  // admin key on the clipboard so "add deployment" is paste-and-go.
  // Opt out (CI / headless / "stop opening tabs") with BRIGADE_NO_BROWSER=1.
  if (process.env.BRIGADE_NO_BROWSER !== "1") {
    try {
      if (process.platform === "win32") {
        // `start` needs the empty-title arg; clip reads the key from stdin.
        spawn("cmd", ["/c", "start", "", dashboardUrl], { stdio: "ignore", detached: true }).unref();
        const clip = spawn("clip", [], { stdio: ["pipe", "ignore", "ignore"] });
        clip.stdin.end(adminKey);
        console.log(`\x1b[32m▌   (dashboard opened · admin key copied to clipboard — just paste it)\x1b[0m`);
      } else if (process.platform === "darwin") {
        spawn("open", [dashboardUrl], { stdio: "ignore", detached: true }).unref();
        const pb = spawn("pbcopy", [], { stdio: ["pipe", "ignore", "ignore"] });
        pb.stdin.end(adminKey);
        console.log(`\x1b[32m▌   (dashboard opened · admin key copied to clipboard — just paste it)\x1b[0m`);
      } else {
        spawn("xdg-open", [dashboardUrl], { stdio: "ignore", detached: true }).unref();
        console.log(`\x1b[32m▌   (dashboard opened — admin key is in .convex-data/admin-key.txt)\x1b[0m`);
      }
    } catch {
      /* best-effort — the printed instructions above always work */
    }
  }
  console.log(``);
});

// ---------------------------------------------------------------------------
// 7. Graceful shutdown
// ---------------------------------------------------------------------------
let shuttingDown = false;
function shutdown(code = 0) {
  if (shuttingDown) return;
  shuttingDown = true;
  console.log(`\n\x1b[36m▌ Stopping...\x1b[0m`);
  try { dashboardServer.close(); } catch {}
  try { backend.kill("SIGTERM"); } catch {}
  setTimeout(() => process.exit(code), 500);
}
process.on("SIGINT",  () => shutdown(0));
process.on("SIGTERM", () => shutdown(0));

// Kick off the function push LAST — after `shuttingDown` above is
// initialized (pushFunctionsWhenReady reads it; an earlier call site hit
// the let-binding TDZ and crashed the whole orchestrator at startup).
void pushFunctionsWhenReady();
